name: with_converter_annotation
description: A new Flutter package project
version: 0.0.1
homepage: https://github.com/htsuruo/with_converter_generator

environment:
  sdk: '>=3.1.5 <4.0.0'

dev_dependencies:
  flutter_lints: ^3.0.1
