targets:
  $default:
    builders:
      firestore_converter_gen:
        enabled: true
        generate_for:
          exclude:
            - test
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - lines_longer_than_80_chars
            - unused_element

builders:
  firestore_converter_gen:
    import: 'package:firestore_converter_gen/builder.dart'
    builder_factories: ['firestoreConverterBuilder']
    build_extensions: { '.dart': ['firestore_converter.g.dart'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
