name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  cloud_firestore: ^4.13.0
  flutter:
    sdk: flutter
  freezed_annotation:
  json_annotation:
  with_converter_annotation:
    path: ../with_converter_annotation

dev_dependencies:
  build_runner: ^2.4.6
  freezed:
  json_serializable:
  pedantic_mono: ^1.24.0+1
  with_converter_generator:
    path: ../with_converter_generator

flutter:
  uses-material-design: true
