name: with_converter_generator
repository: https://github.com/htsuruo/with_converter_generator
packages:
  - packages/**

command:
  environment:
    sdk: ^3.1.0
  bootstrap:
    dev_dependencies:
      build_runner: ^2.4.6
      pedantic_mono: ^1.24.0+1

ide:
  intellij: false
