name: firestore_converter_annotation
description: A new Flutter package project
version: 0.0.1
homepage: https://github.com/htsuruo/firestore_converter_gen

environment:
  sdk: ^3.1.0

dependencies:
  cloud_firestore: ^4.13.0
  json_annotation: ^4.8.1

dev_dependencies:
  pedantic_mono: ^1.24.0+1
