name: firestore_converter_annotation
description: Annotation that support typed converter code generation via the
  `firestore_converter_gen` package.
version: 0.0.1
homepage: https://github.com/htsuruo/firestore_converter_gen
topics:
  - build-runner
  - codegen
  - cloud_firestore

environment:
  sdk: ^3.1.0

dependencies:
  cloud_firestore: ^4.13.0
  json_annotation: ^4.8.1

dev_dependencies:
  pedantic_mono: ^1.24.0+1
