targets:
  $default:
    builders:
      with_converter_generator:
        enabled: true
        generate_for:
          exclude:
            - test
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - 'type=lint'

builders:
  with_converter_generator:
    import: 'package:with_converter_generator/builder.dart'
    builder_factories: ['withConverterBuilder']
    build_extensions: { '.dart': ['.g.dart'] }
    auto_apply: dependents
    build_to: source
    applies_builders: ['source_gen|combining_builder']
