targets:
  $default:
    builders:
      with_converter_generator:
        enabled: true
        generate_for:
          exclude:
            - test
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - lines_longer_than_80_chars
            - unused_element

builders:
  with_converter_generator:
    import: 'package:with_converter_generator/builder.dart'
    builder_factories: ['withConverterBuilder']
    build_extensions: { '.dart': ['with_converter.g.dart'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder']
