name: with_converter_generator
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/htsuruo/with_converter_generator

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  analyzer: '^6.3.0'
  build: ^2.4.1
  build_config: ^1.1.1
  source_gen: ^1.4.0

dev_dependencies:
  flutter_lints: ^3.0.1
