name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  cloud_firestore: ^4.13.0
  json_annotation: ^4.8.1
  with_converter_annotation:
    path: ../../with_converter_annotation

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  pedantic_mono: ^1.24.0+1
  with_converter_generator:
    path: ..

flutter:
  uses-material-design: true
