name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  cloud_firestore: ^4.13.0
  with_converter_annotation:
    path: ../../with_converter_annotation

dev_dependencies:
  build_runner:
  pedantic_mono:
  with_converter_generator:
    path: ..

flutter:
  uses-material-design: true
