name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  with_converter_annotation:
    path: ../../with_converter_annotation

dev_dependencies:
  with_converter_generator:
    path: ..
  build_runner: ^2.4.6
  pedantic_mono: ^1.24.0+1

flutter:
  uses-material-design: true
